version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/Chicago"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(github-actions)"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/Chicago"
    cooldown:
      default-days: 14
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(npm)"
    labels:
      - "dependencies"
      - "npm"

