name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - type: pre-exclude
    when:
      label: skip-changelog
  - type: changelog
    title: Breaking changes
    semver-increment: minor
    when:
      label: breaking-change
  - type: changelog
    title: Features and enhancements
    semver-increment: minor
    when:
      labels:
        - feature
        - enhancement
  - type: changelog
    title: Bug fixes
    semver-increment: patch
    when:
      labels:
        - bug
        - bugfix
  - type: changelog
    title: Documentation
    when:
      label: documentation
  - type: changelog
    title: Dependencies and maintenance
    when:
      labels:
        - dependencies
        - maintenance
        - ci
  - type: version-resolver
    semver-increment: major
    when:
      label: major
  - type: version-resolver
    semver-increment: minor
    when:
      label: minor
  - type: version-resolver
    semver-increment: patch
    when:
      label: patch
  - type: version-resolver
    semver-increment: patch

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES
